version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: course
      MYSQL_ROOT_PASSWORD: ${spring.datasource.password}
    ports:
      - '3316:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql

  app:
    build: .
    container_name: springboot
    ports:
      - '8090:8080'
    environment:
      SPRING_DATASOURCE_URL: ${spring.datasource.url}
      SPRING_DATASOURCE_USERNAME: ${spring.datasource.username}
      SPRING_DATASOURCE_PASSWORD: ${spring.datasource.password}
    depends_on:
      - mysql
    networks:
      - course-network

volumes:
  mysql-data:

networks:
  springboot-mysql:
    driver: bridge
